ctest_add (test_mathfunc.TestMathFunc)
Test method add(a, b) ... ok
test_minus (test_mathfunc.TestMathFunc)
Test method minus(a, b) ... ok
test_divide (test_mathfunc.TestMathFunc)
Test method divide(a, b) ... FAIL

======================================================================
FAIL: test_divide (test_mathfunc.TestMathFunc)
Test method divide(a, b)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\$$$Python20180504\0笔记&代码 20180315\unittest\test_mathfunc.py", line 24, in test_divide
    self.assertEqual(3, divide(5, 2))
AssertionError: 3 != 2.5

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
test_add (test_mathfunc.TestMathFunc)
Test method add(a, b) ... ok
test_minus (test_mathfunc.TestMathFunc)
Test method minus(a, b) ... ok
test_divide (test_mathfunc.TestMathFunc)
Test method divide(a, b) ... FAIL

======================================================================
FAIL: test_divide (test_mathfunc.TestMathFunc)
Test method divide(a, b)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\$$$Python20180504\0笔记&代码 20180315\unittest\test_mathfunc.py", line 24, in test_divide
    self.assertEqual(3, divide(5, 2))
AssertionError: 3 != 2.5

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
test_add (test_mathfunc.TestMathFunc)
Test method add(a, b) ... ok
test_minus (test_mathfunc.TestMathFunc)
Test method minus(a, b) ... ok
test_divide (test_mathfunc.TestMathFunc)
Test method divide(a, b) ... skipped "I don't want to run this case."

----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK (skipped=1)
